CREATE OR REPLACE FUNCTION current_age()
RETURNS TRIGGER AS $$
DECLARE d_age NUMERIC;
DECLARE age INTERVAL;
BEGIN
	SELECT AGE(a.dob) INTO age FROM app_user a WHERE a.email = NEW.driver;
	SELECT EXTRACT(YEAR FROM age) INTO d_age;
	IF d_age >= 18 THEN
		RETURN NEW;
	ELSE
		RAISE EXCEPTION 'Driver age is below 18!';
		RETURN NULL;
	END IF;
END; $$
LANGUAGE PLPGSQL;
	
CREATE TRIGGER check_legal_age
BEFORE INSERT OR UPDATE
ON drive
FOR EACH ROW
EXECUTE PROCEDURE current_age(); 